### ISSUE TITLE
ERD chart

### ISSUE THREAD

**Issue by DanielBabcock** [MontroseMagpies/bangazon_orientation_api#32]
![image](https://user-images.githubusercontent.com/28121171/31905781-e559a094-b7f4-11e7-8988-0a7bcdbc54e0.png)

**Comment by jasminecain** [comment]
<img width="716" alt="erd 10 23 17" src="https://user-images.githubusercontent.com/6125785/31918206-1ac6cde8-b821-11e7-9a77-5887d9b2638a.png">
